# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(max_length=4)),
                ('movie_title', models.CharField(max_length=200)),
                ('release_date', models.IntegerField(max_length=4)),
                ('imdb_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Rater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=3)),
                ('age', models.IntegerField(max_length=3)),
                ('gender', models.CharField(max_length=1)),
                ('occupation', models.CharField(max_length=200)),
                ('zip_code', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(max_length=1)),
                ('timestamp', models.IntegerField(max_length=9)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedata.Movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedata.Rater')),
            ],
        ),
    ]
